language: python
python:
- 2.7
services:
- docker
install:
- docker build -t nginx-proxy .
- docker run -d -p 127.0.0.1:80:80 --name proxy1 nginx-proxy
script:
- docker ps | grep -q nginx-proxy
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
- export REPO=rjarow/nginx-proxy
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u=$DOCKER_USER -p=$DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER; docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG