language: python
python:
- 2.7
services:
- docker
install:
- docker build -t nginx-proxy .
- docker run -d -p 127.0.0.1:80:80 --name proxy1 nginx-proxy
script:
- docker ps | grep -q nginx-proxy
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
- export REPO=rjarow/nginx-proxy
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u=$DOCKER_USER -p=$DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER; docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG
env:
  global:
    secure: "ZFeF7g7kHgEvIKVF3yQvoEij5YPOeoGd1pHQuBidL1SbnGIvgR3VsZq9exdMvl63xiQWkGvldXTXGGc16MzomDTwP2pFF620W7HL1/33PcNSh5Y2ptYzXEu+qfd569/xRFbqVOpGSjm7QyerphT4dU1gvCAzqO9oKQYNgg/r+2EkvKAPOYKSDcNDupbjOt/ZJzisVLSGGpglYvwhCZ4JsspyMcwb9HPOCGGGUAr3zs8DWKRuuS5Nbp2rocOzVC5A9xtw0CsrBtXMtw1kXbG3xbAJLpm8celdx9e+D2foGDRWV+qBn6N356j8/KAejKKaqVI/KGg8ZzKU08n1WZsuitvY0jXU0RwMu/IYBf17JIDH3kR0YInnrTxsxLI37Bf48s+N8zyKR3okjdT5jkLona0SX3USjdg9yYakonZEvmC4q4yXxCkS11BXNuTk7czVwMcct4C1Att3l8Ow88/7fRXZvBJ1SRwj7fVnUcOtgViqBDGFZTulzq2kS4t4ayZN7YpyTy/vay8GgCsl0bn3q7ljjjtpG+G6V2Kt/mFSPXmow41Yak+P+HTOjSWtXp0FwofEhB5JI4o66ddlpGdxWVA860EMiyCDb1HftAxPBtF9nPbF51+tIoMnFb/Ls0NgOsp3w4xAkbDOFK41vV/geoHq9K3fgrPMkCIbEEbLkFo=" # DOCKER_USER
    secure: "BGBVnFkQh6M66jMGHf0RxwFCdYLuw8S2eUYCy2jFI2Xri+q6Bm9HUKBZMQ3FRF0PTtFmaj9GC3ehsnFxnDk/ueji9WPtmM4WQ6UrPVv5C3noH183M9yC9bbXubpBQQLQQLAQRnCSR5HTk10+FE0wnvEFPMduzuecie0LvuausnGiNqzmRTYKw5fNuVTp4EHjBZoY0d3oxGYdGcshBi+RAjzYnfzLRmuS4Fj9/5SJ6fFaGyOx7EDDT+8CDzYGylgtyb29d2WTklvbvXSaYAgdHg6NbN4wmsTXccRczMkShq3gsacwZdcvopUbV3y/LVbQEuah/aeyFH6Mf+y7K8CDzdaSA/Dc8jCbvqA8Psy+aTO4/ET2UOfz41kuFoSZes/JsqYrdhPJUkIIl4AH03aZGw+S1TjqAIjSJRojtOzlqN4G28qq1iS5RCNu7sfhxshGDPgeTK7C4FzjNwZwbWx32cj05MhzBbbWFrCqygZlzB9Sap2c58TuC8OJIlQuCln6AqrHHocKbLPa0PF8MxhnlRVtihN7DhpovWSIqVK8dhnPZss379ZyLDs8kQBkArP2s7x5JLseuNXpK3qaXtDVyWZyXUkds6skmtePdJh+V0CN2AEGBMoGkLOekFvgV2FrPM8XgPkwta2cTyhoN4kvMzi2nsTJW9rGwxGDQWirzNw=" # DOCKER_PASS
