language: python
python:
- 2.7
services:
- docker
install:
- docker build -t nginx-proxy .
- docker run -d -p 127.0.0.1:80:80 --name proxy1 nginx-proxy
script:
- docker ps | grep -q nginx-proxy
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
- export REPO=rjarow/nginx-proxy
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER; docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG
env:
  global:
    secure: P8EF0kIOfEbQDUOctmjocNuwuGwbPBy02OByUdKdjCZjZztwqSzaZN/zGJDrnOIjvVEcr1uzMvSVjedLiZR1PHucjQtUyY6vmdb65BzA2Y//9o+lBnKOw8FX8XcCdiASx7farFPFE1Ww1iUsfDqDn3yzdlSWl/jx1gV0KLqj1IDv4tkE6hCLQBI6muJCY3/pVavSnH9PzZHji5oC9lMGNpvrzwf70cPm2sKg3H5InR0V2McsagBNu+dd+EtcDUPCBg5MCTJgSJ484+zChJDMBHf2mBMvUqseDoTRsXgBna81+CLd2Nf06dQyDVjP41IKChaZ53QXVXiXGQdhIC4iI3iAD/3TCTh8z/ML8owyP8A/DERCimPe6U57vgbxEtVDymcSpAZL1ozytCZTg1vftHse/EUrRLJ4wf0lUCZBxRbBWyzRp3m9Vc+7GLBWynGQjdN6yX42/QTDBV/2YSKbdVGofG1+8fR3C8HIKAitsWxVfNzRS1e+g8WhbibHC1mxzqD3E39dAReZwOoCUSpX+L8lKi3bzCR/IZHtUwfgd4ygsxMKqswuD281hUo1FXL8W0QvdEEGURdPD+MgIgJNAsGhs/02Ww51lfvnZhIWK98AhUN7MJvfZXjAW8WWwJgCzP30r9YcNPUphKPCq8lALYKmvyiyGUXeh95WGnnR3nw=
dd:
  secure: Jd7eg7tbtlFpnec4Dgv9xgGFo0YemNkLawoKQg///b+0G8zPSX6N+VghEBd6B1yQiHh6XNyZk4Du7roGiOtKPnYV+XWlqJH9fZ4Da4XyBhbAsZs4ixdN74PjIPUqeQpTVxum4Nq+rmLKiphq1NPrDnW7KxXvoQYORv4job/0zNtxNaPd7bzU0i0ChSRpiGwHHhLZ7TJqYQMk/G2tiDHalZwd8KBRRUb2qj6tp7fezWxuuivCvc1xekQDnwN9DGOLQ7gzPqm8vMc9/d2MLRBnkbj/ErRhUotwjsq8nMreO11ETjHsR3/Q0v/FbJKBgNZxfSB1NZiYBI+wjVMz/lzoAXBYE4qeOJixvzPkHZysE4mBMkThu3Mmz2pxpH60f0w5Z1uaZfT0H1mXmK9Wp+ars0jvxl4261/G42pvM7RR0svgXN1wKkYdJ7eaheTlI4ArxmPesdn5viAJewhrSz/dEN0eAowwocA4tzSQqFHI4n7mLjm1AnvwmloQLUvRPMeaoCUFJzzuXSk+N6YWGe4hRix5eGKMYt9p03RSjMeKqt1n93Bet21YYzdk4yabPNnusY3TFfzrmVW9kZYdHK7OD3ulMCc/6IehJ9Tya5wjw5vvGTIe/xAb4JAZXrIb63v5CZehjCVed0VZmVUv8Mmngb2DAONrtTRGyNtzmiVKBxI=
